config/routes.rb
Rails.application.routes.draw do
  resources :ama1s
  resources :careyouals
  resources :careyouallls
  resources :line
  resources :push_messages
  get 'push/messages'
  #post '/line/webhook', to: 'line#webhook'
  resources :careyoualls
  resources :care_yous
  resources :careyous
  resources :testabcs
  resources :keyword_mappings
  resources :push_messages, only: [:new, :create]
  post 'line/webhook'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ama1.rb
class Ama1 < ApplicationRecord
end

app/models/ama2.rb
class Ama2 < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_you.rb
class CareYou < ApplicationRecord
end

app/models/careyou.rb
class Careyou < ApplicationRecord
end

app/models/careyoual.rb
class Careyoual < ApplicationRecord
end

app/models/careyouall.rb
class Careyouall < ApplicationRecord
  self.abstract_class = true
	
end

app/models/careyoualll.rb
class Careyoualll < ApplicationRecord
end

app/models/careyoudatum.rb
class Careyoudatum < ApplicationRecord
end

app/models/cy.rb
class Cy < ApplicationRecord
end

app/models/keyword_mapping.rb
class KeywordMapping < ApplicationRecord 
end

app/models/push_message.rb
class PushMessage < ApplicationRecord
end

app/models/testabc.rb
class Testabc < ApplicationRecord
end

app/controllers/testabcs_controller.rb
class TestabcsController < ApplicationController
  before_action :set_testabc, only: [:show, :edit, :update, :destroy]

  # GET /testabcs
  # GET /testabcs.json
  def index
    @testabcs = Testabc.all
  end

  # GET /testabcs/1
  # GET /testabcs/1.json
  def show
  end

  # GET /testabcs/new
  def new
    @testabc = Testabc.new
  end

  # GET /testabcs/1/edit
  def edit
  end

  # POST /testabcs
  # POST /testabcs.json
  def create
    @testabc = Testabc.new(testabc_params)

    respond_to do |format|
      if @testabc.save
        format.html { redirect_to @testabc, notice: 'Testabc was successfully created.' }
        format.json { render :show, status: :created, location: @testabc }
      else
        format.html { render :new }
        format.json { render json: @testabc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testabcs/1
  # PATCH/PUT /testabcs/1.json
  def update
    respond_to do |format|
      if @testabc.update(testabc_params)
        format.html { redirect_to @testabc, notice: 'Testabc was successfully updated.' }
        format.json { render :show, status: :ok, location: @testabc }
      else
        format.html { render :edit }
        format.json { render json: @testabc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testabcs/1
  # DELETE /testabcs/1.json
  def destroy
    @testabc.destroy
    respond_to do |format|
      format.html { redirect_to testabcs_url, notice: 'Testabc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testabc
      @testabc = Testabc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testabc_params
      params.require(:testabc).permit(:id, :w)
    end
end

app/helpers/ama1s_helper.rb
module Ama1sHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/care_yous_helper.rb
module CareYousHelper
end

app/helpers/careyouals_helper.rb
module CareyoualsHelper
end

app/helpers/careyous_helper.rb
module CareyousHelper
end

app/helpers/cies_helper.rb
module CiesHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/push_helper.rb
module PushHelper
end

app/helpers/testabcs_helper.rb
module TestabcsHelper
end

app/views/testabcs/_form.html.erb
<%= form_with(model: testabc, local: true) do |form| %>
  <% if testabc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testabc.errors.count, "error") %> prohibited this testabc from being saved:</h2>

      <ul>
      <% testabc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :w %>
    <%= form.text_field :w %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testabcs/edit.html.erb
<h1>Editing Testabc</h1>

<%= render 'form', testabc: @testabc %>

<%= link_to 'Show', @testabc %> |
<%= link_to 'Back', testabcs_path %>

app/views/testabcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testabcs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>W</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testabcs.each do |testabc| %>
      <tr>
        <td><%= testabc.id %></td>
        <td><%= testabc.w %></td>
        <td><%= link_to 'Show', testabc %></td>
        <td><%= link_to 'Edit', edit_testabc_path(testabc) %></td>
        <td><%= link_to 'Destroy', testabc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testabc', new_testabc_path %>

app/views/testabcs/new.html.erb
<h1>New Testabc</h1>

<%= render 'form', testabc: @testabc %>

<%= link_to 'Back', testabcs_path %>

app/views/testabcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @testabc.id %>
</p>

<p>
  <strong>W:</strong>
  <%= @testabc.w %>
</p>

<%= link_to 'Edit', edit_testabc_path(@testabc) %> |
<%= link_to 'Back', testabcs_path %>