config/routes.rb
Rails.application.routes.draw do
  resources :ama1s
  resources :careyouals
  resources :careyouallls
  resources :line
  resources :push_messages
  get 'push/messages'
  #post '/line/webhook', to: 'line#webhook'
  resources :careyoualls
  resources :care_yous
  resources :careyous
  resources :testabcs
  resources :keyword_mappings
  resources :push_messages, only: [:new, :create]
  post 'line/webhook'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ama1.rb
class Ama1 < ApplicationRecord
end

app/models/ama2.rb
class Ama2 < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_you.rb
class CareYou < ApplicationRecord
end

app/models/careyou.rb
class Careyou < ApplicationRecord
end

app/models/careyoual.rb
class Careyoual < ApplicationRecord
end

app/models/careyouall.rb
class Careyouall < ApplicationRecord
  self.abstract_class = true
	
end

app/models/careyoualll.rb
class Careyoualll < ApplicationRecord
end

app/models/careyoudatum.rb
class Careyoudatum < ApplicationRecord
end

app/models/cy.rb
class Cy < ApplicationRecord
end

app/models/keyword_mapping.rb
class KeywordMapping < ApplicationRecord 
end

app/models/push_message.rb
class PushMessage < ApplicationRecord
end

app/models/testabc.rb
class Testabc < ApplicationRecord
end

app/controllers/care_yous_controller.rb
class CareYousController < ApplicationController
  before_action :set_care_you, only: [:show, :edit, :update, :destroy]

  # GET /care_yous
  # GET /care_yous.json
  def index
    @care_yous = CareYou.all
  end

  # GET /care_yous/1
  # GET /care_yous/1.json
  def show
  end

  # GET /care_yous/new
  def new
    @care_you = CareYou.new
  end

  # GET /care_yous/1/edit
  def edit
  end

  # POST /care_yous
  # POST /care_yous.json
  def create
    @care_you = CareYou.new(care_you_params)

    respond_to do |format|
      if @care_you.save
        format.html { redirect_to @care_you, notice: 'Care you was successfully created.' }
        format.json { render :show, status: :created, location: @care_you }
      else
        format.html { render :new }
        format.json { render json: @care_you.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_yous/1
  # PATCH/PUT /care_yous/1.json
  def update
    respond_to do |format|
      if @care_you.update(care_you_params)
        format.html { redirect_to @care_you, notice: 'Care you was successfully updated.' }
        format.json { render :show, status: :ok, location: @care_you }
      else
        format.html { render :edit }
        format.json { render json: @care_you.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_yous/1
  # DELETE /care_yous/1.json
  def destroy
    @care_you.destroy
    respond_to do |format|
      format.html { redirect_to care_yous_url, notice: 'Care you was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_you
      @care_you = CareYou.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_you_params
      params.require(:care_you).permit(:name, :a1, :b1)
    end
end

app/controllers/careyous_controller.rb
class CareyousController < ApplicationController
  before_action :set_careyou, only: [:show, :edit, :update, :destroy]

  # GET /careyous
  # GET /careyous.json
  def index
    @careyous = Careyou.all
  end

  # GET /careyous/1
  # GET /careyous/1.json
  def show
  end

  # GET /careyous/new
  def new
    @careyou = Careyou.new
  end

  # GET /careyous/1/edit
  def edit
  end

  # POST /careyous
  # POST /careyous.json
  def create
    @careyou = Careyou.new(careyou_params)

    respond_to do |format|
      if @careyou.save
        format.html { redirect_to @careyou, notice: 'Careyou was successfully created.' }
        format.json { render :show, status: :created, location: @careyou }
      else
        format.html { render :new }
        format.json { render json: @careyou.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /careyous/1
  # PATCH/PUT /careyous/1.json
  def update
    respond_to do |format|
      if @careyou.update(careyou_params)
        format.html { redirect_to @careyou, notice: 'Careyou was successfully updated.' }
        format.json { render :show, status: :ok, location: @careyou }
      else
        format.html { render :edit }
        format.json { render json: @careyou.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /careyous/1
  # DELETE /careyous/1.json
  def destroy
    @careyou.destroy
    respond_to do |format|
      format.html { redirect_to careyous_url, notice: 'Careyou was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_careyou
      @careyou = Careyou.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def careyou_params
      params.require(:careyou).permit(:id)
    end
end

app/controllers/cies_controller.rb
class CiesController < ApplicationController
  before_action :set_cy, only: [:show, :edit, :update, :destroy]

  # GET /cies
  # GET /cies.json
  def index
    @cies = Cy.all
  end

  # GET /cies/1
  # GET /cies/1.json
  def show
  end

  # GET /cies/new
  def new
    @cy = Cy.new
  end

  # GET /cies/1/edit
  def edit
  end

  # POST /cies
  # POST /cies.json
  def create
    @cy = Cy.new(cy_params)

    respond_to do |format|
      if @cy.save
        format.html { redirect_to @cy, notice: 'Cy was successfully created.' }
        format.json { render :show, status: :created, location: @cy }
      else
        format.html { render :new }
        format.json { render json: @cy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cies/1
  # PATCH/PUT /cies/1.json
  def update
    respond_to do |format|
      if @cy.update(cy_params)
        format.html { redirect_to @cy, notice: 'Cy was successfully updated.' }
        format.json { render :show, status: :ok, location: @cy }
      else
        format.html { render :edit }
        format.json { render json: @cy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cies/1
  # DELETE /cies/1.json
  def destroy
    @cy.destroy
    respond_to do |format|
      format.html { redirect_to cies_url, notice: 'Cy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cy
      @cy = Cy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cy_params
      params.require(:cy).permit(:a, :b, :c, :d, :e, :f, :g, :h, :i, :j, :k, :l, :m, :n, :o, :p, :q, :r, :s, :t, :u, :v, :w, :x, :y, :z)
    end
end

app/helpers/ama1s_helper.rb
module Ama1sHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/care_yous_helper.rb
module CareYousHelper
end

app/helpers/careyoualls_helper.rb
module CareyouallsHelper
end

app/helpers/careyouals_helper.rb
module CareyoualsHelper
end

app/helpers/careyous_helper.rb
module CareyousHelper
end

app/helpers/cies_helper.rb
module CiesHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/push_helper.rb
module PushHelper
end

app/helpers/testabcs_helper.rb
module TestabcsHelper
end

app/views/care_yous/_form.html.erb
<%= form_with(model: care_you, local: true) do |form| %>
  <% if care_you.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(care_you.errors.count, "error") %> prohibited this care_you from being saved:</h2>

      <ul>
      <% care_you.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :a1 %>
    <%= form.text_field :a1 %>
  </div>

  <div class="field">
    <%= form.label :b1 %>
    <%= form.text_field :b1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/care_yous/edit.html.erb
<h1>Editing Care You</h1>

<%= render 'form', care_you: @care_you %>

<%= link_to 'Show', @care_you %> |
<%= link_to 'Back', care_yous_path %>

app/views/care_yous/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Care Yous</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>A1</th>
      <th>B1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @care_yous.each do |care_you| %>
      <tr>
        <td><%= care_you.name %></td>
        <td><%= care_you.a1 %></td>
        <td><%= care_you.b1 %></td>
        <td><%= link_to 'Show', care_you %></td>
        <td><%= link_to 'Edit', edit_care_you_path(care_you) %></td>
        <td><%= link_to 'Destroy', care_you, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Care You', new_care_you_path %>

app/views/care_yous/new.html.erb
<h1>New Care You</h1>

<%= render 'form', care_you: @care_you %>

<%= link_to 'Back', care_yous_path %>

app/views/care_yous/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @care_you.name %>
</p>

<p>
  <strong>A1:</strong>
  <%= @care_you.a1 %>
</p>

<p>
  <strong>B1:</strong>
  <%= @care_you.b1 %>
</p>

<%= link_to 'Edit', edit_care_you_path(@care_you) %> |
<%= link_to 'Back', care_yous_path %>

app/views/careyous/_form.html.erb
<%= form_with(model: careyou, local: true) do |form| %>
  <% if careyou.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(careyou.errors.count, "error") %> prohibited this careyou from being saved:</h2>

      <ul>
      <% careyou.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/careyous/edit.html.erb
<h1>Editing Careyou</h1>

<%= render 'form', careyou: @careyou %>

<%= link_to 'Show', @careyou %> |
<%= link_to 'Back', careyous_path %>

app/views/careyous/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Careyous</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @careyous.each do |careyou| %>
      <tr>
        <td><%= careyou.id %></td>
        <td><%= link_to 'Show', careyou %></td>
        <td><%= link_to 'Edit', edit_careyou_path(careyou) %></td>
        <td><%= link_to 'Destroy', careyou, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Careyou', new_careyou_path %>

app/views/careyous/new.html.erb
<h1>New Careyou</h1>

<%= render 'form', careyou: @careyou %>

<%= link_to 'Back', careyous_path %>

app/views/careyous/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @careyou.id %>
</p>

<%= link_to 'Edit', edit_careyou_path(@careyou) %> |
<%= link_to 'Back', careyous_path %>