config/routes.rb
Rails.application.routes.draw do
  resources :ama1s
  resources :careyouals
  resources :careyouallls
  resources :line
  resources :push_messages
  get 'push/messages'
  #post '/line/webhook', to: 'line#webhook'
  resources :careyoualls
  resources :care_yous
  resources :careyous
  resources :testabcs
  resources :keyword_mappings
  resources :push_messages, only: [:new, :create]
  post 'line/webhook'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ama1.rb
class Ama1 < ApplicationRecord
end

app/models/ama2.rb
class Ama2 < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_you.rb
class CareYou < ApplicationRecord
end

app/models/careyou.rb
class Careyou < ApplicationRecord
end

app/models/careyoual.rb
class Careyoual < ApplicationRecord
end

app/models/careyouall.rb
class Careyouall < ApplicationRecord
  self.abstract_class = true
	
end

app/models/careyoualll.rb
class Careyoualll < ApplicationRecord
end

app/models/careyoudatum.rb
class Careyoudatum < ApplicationRecord
end

app/models/cy.rb
class Cy < ApplicationRecord
end

app/models/keyword_mapping.rb
class KeywordMapping < ApplicationRecord 
end

app/models/push_message.rb
class PushMessage < ApplicationRecord
end

app/models/testabc.rb
class Testabc < ApplicationRecord
end

app/helpers/ama1s_helper.rb
module Ama1sHelper
end

app/helpers/care_yous_helper.rb
module CareYousHelper
end

app/helpers/careyouals_helper.rb
module CareyoualsHelper
end

app/helpers/careyous_helper.rb
module CareyousHelper
end

app/helpers/cies_helper.rb
module CiesHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/push_helper.rb
module PushHelper
end

app/helpers/push_messages_helper.rb
module PushMessagesHelper
end

app/helpers/testabcs_helper.rb
module TestabcsHelper
end

app/views/push_messages/_form.html.erb
<%= form_with(model: push_message, local: true) do |form| %>
  <% if push_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(push_message.errors.count, "error") %> prohibited this push_message from being saved:</h2>

      <ul>
      <% push_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :a %>
    <%= form.text_field :a %>
  </div>

  <div class="field">
    <%= form.label :b %>
    <%= form.text_field :b %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/push_messages/edit.html.erb
<h1>Editing Push Message</h1>

<%= render 'form', push_message: @push_message %>

<%= link_to 'Show', @push_message %> |
<%= link_to 'Back', push_messages_path %>

app/views/push_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Push Messages</h1>

<table>
  <thead>
    <tr>
      <th>A</th>
      <th>B</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @push_messages.each do |push_message| %>
      <tr>
        <td><%= push_message.a %></td>
        <td><%= push_message.b %></td>
        <td><%= link_to 'Show', push_message %></td>
        <td><%= link_to 'Edit', edit_push_message_path(push_message) %></td>
        <td><%= link_to 'Destroy', push_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Push Message', new_push_message_path %>

app/views/push_messages/new.html.erb
<h1>New Push Message</h1>

<%= form_with(url: '/push_messages', local: true) do |form| %>
  <%= text_area_tag 'text' %>
  <%= submit_tag "送出" %>
<% end %>

app/views/push_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @push_message.a %>
</p>

<p>
  <strong>B:</strong>
  <%= @push_message.b %>
</p>

<%= link_to 'Edit', edit_push_message_path(@push_message) %> |
<%= link_to 'Back', push_messages_path %>